version: '3.9'

services:
  api:
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - ./envoriments/.env.dev
    depends_on:
      - db
      - minio

  db:
    image: postgres:15
    container_name: janio_postgres_prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: x9CyeqPlZ7aREt6J
      POSTGRES_DB: janio_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d x9CyeqPlZ7aREt6J']
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: janio_minio_prod
    environment:
      MINIO_ROOT_USER: janioadmin
      MINIO_ROOT_PASSWORD: 9U0W1FAp4a7qdz59
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  pgdata:
  minio_data:
